export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE';
export const RESET_NEW_ITEM = 'RESET_NEW_ITEM';
export const TOGGLE_TIMER = 'TOGGLE_TIMER';
export const TOGGLE_TIMER_SUCCESS = 'TOGGLE_TIMER_SUCCESS';
